## 2-ое задание

In [8]:
import numpy as np

In [117]:
# true results
y_t = ['c','c','c','c','c','c', 'f','f','f','f','f','f','f','f','f','f', 'h','h','h','h','h','h','h','h','h']
#predicted results
y_p = ['c','c','c','c','h','f', 'c','c','c','c','c','c','h','h','f','f', 'c','c','c','h','h','h','h','h','h']

a=np.array([[y_p[0:6].count('c'), y_p[0:6].count('f'), y_p[0:6].count('h')], 
            [y_p[6:16].count('c'), y_p[6:16].count('f'), y_p[6:16].count('h')],
            [y_p[16:25].count('c'), y_p[16:25].count('f'), y_p[16:25].count('h')]])

In [118]:
#сделала матрицу ошибок для каждого класса и распределила на true positive false positive и тд
tpc=4
fpc=9
fnc=2
tnc=10

tpf=2
fpf=1
fnf=8
tnf=14

tph=6
fph=3
fnh=3
tnh=13

#метрики для CAT
#precision
cat_pr = round(tpc/(fpc+tpc),3)
print(cat_pr)

#recall
cat_r=round(tpc/(tpc+fnc),3)
print(cat_r)

#f1-score
cat_f1=round(2*cat_pr*cat_r/(cat_pr+cat_r),3)
print(cat_f1)

#support
cat_sup=y_t.count('c')
fish_sup=y_t.count('f')
hen_sup=y_t.count('h')
print('\n','support:', sep='')
print('cat', cat_sup)
print('fish',fish_sup)
print('hen', hen_sup)

0.308
0.667
0.421

support:
cat 6
fish 10
hen 9


In [119]:
#метрики для FISH
#precision
fish_pr = round(tpf/(fpf+tpf),3)
print(fish_pr)

#recall
fish_r=round(tpf/(tpf+fnf),3)
print(fish_r)

#f1-score
fish_f1= round(2*fish_pr*fish_r/(fish_pr+fish_r),3)
print(fish_f1)

0.667
0.2
0.308


In [120]:
#метрики для HEN
#precision
hen_pr = round(tph/(fph+tph),3)
print(hen_pr)

#recall
hen_r=round(tph/(tph+fnh),3)
print(hen_r)

#f1-score
hen_f1=round(2*hen_pr*hen_r/(hen_pr+hen_r),3)
print(hen_f1)

0.667
0.667
0.667


In [121]:
accuracy=(tpc+tpf+tph)/25

#macro average
mac_avgp= round((cat_pr+fish_pr+hen_pr)/3,3)
mac_avgr= round((cat_r+fish_r+hen_r)/3,3)
mac_avgf= round((cat_f1+fish_f1+hen_f1)/3,3)

#weighted average
wg_avgp=round((cat_pr*cat_sup/25+fish_pr*fish_sup/25+hen_pr*hen_sup/25),3)
wg_avgr=round((cat_r*cat_sup/25+fish_r*fish_sup/25+hen_r*hen_sup/25),3)
wg_avgf=round((cat_f1*cat_sup/25+fish_f1*fish_sup/25+hen_f1*hen_sup/25),3)

In [123]:
print(a)
print()
print(14*' '+'precision', ' '*3+'recall', '', 'f-1 score', '', 'support')
print()
print(9*' '+'Cat'+' '*5, cat_pr,' '*3, cat_r, ' '*4, cat_f1, ' '*6, cat_sup)
print(8*' '+'Fish'+' '*5, fish_pr, ' '*3, fish_r, ' '*6, fish_f1, ' '*5, fish_sup)
print(9*' '+'Hen'+' '*5, hen_pr,' '*3, hen_r, ' '*4, hen_f1, ' '*6, hen_sup)
print()
print(4*' '+'accuracy'+' '*26, accuracy, ' '*6, 25)
print(3*' '+'macro avg'+' '*5,mac_avgp,' '*3, mac_avgr,' '*4, mac_avgf, ' '*5, 25)
print('weighted avg'+' '*5,wg_avgp, ' '*3, wg_avgr, ' '*5, wg_avgf, ' '*5, 25)

[[4 1 1]
 [6 2 2]
 [3 0 6]]

              precision    recall  f-1 score  support

         Cat      0.308     0.667      0.421        6
        Fish      0.667     0.2        0.308       10
         Hen      0.667     0.667      0.667        9

    accuracy                           0.48        25
   macro avg      0.547     0.511      0.465       25
weighted avg      0.581     0.48       0.464       25
